apiVersion: v1
kind: BuildConfig
metadata:
  #labels:
  #  app: ${LABEL}
  name: hnsesb-sample
spec:
  source:
    type: Binary
    binary: {}      
  output:
    to:
      kind: "ImageStreamTag"
      #name: "image-registry.apps.silver.devops.gov.bc.ca/c5839f-tools/${IMAGE_STREAM_TAG}"
      #name: "image-registry.openshift-image-registry.svc:5000/c5839f-tools/hnsesb:latest"
      namespace: "c5839f-tools"
      name: "hnsesb:hnsesb-ephimeral"
  strategy:
    type: Docker
    dockerStrategy:
      pullSecret:
        name: docker-hub
      # Find the image build instructions in ./Dockerfile
      dockerfilePath: Dockerfile